### ISSUE TITLE
Tasks

### ISSUE THREAD

**Issue by Mono2** [C-C-A-A/CologneProtocol-R#15]
Choose any of the tasks in this list and assign yourself to the corresponding issue. After finishing mark it as complete. 
If you recognize an issue add it to this list and open an new issue, which describes the problem.

**Tasks related to release of repository**
 - [x] Decision about the name of the repository: CologneProtocol or CologneGeostatisticalProtocol
 - [x] Revise `README.md`: add Overview, add links to other solutions in R, check spelling...
 - [x] Change terminology according to table S2 and use short names
 - [x] Revise `EarlyNeolithic.Rmd`: update code snippets, check spelling...
 - [x] Check all comments for spelling
 - [x] Decision about sample data (#2)
 - [x] Add `output\` directory to the repository

**Tasks related to use of the protocol**
(all issues are listed here)
 - [x] Add an option weather border points of Thiessen polygone should be used or not (#1)
 - [x] How to handle the lag distance in variogram function? (#3)
 - [x] Option for fitting theoretical variogram (#4)
 - [x] Add a section for the definition of variables in the first script `00_LEC.R` (#7)
 - [x] How to set nugget value in krige function (#10)
 - [x] Merging the tables `isoline_stats`, `isoline_increase` and `isoline_diff` into one table (#11)
 - [x] Cartesian vs. ellipsoidal coordinates: `gstat::gDistance` requires cartesian coordinates (#8)
 - [x] deldir::deldir adds a 10% buffer when creating Voronoi diagrams (#16)
 - [ ] Solve the problem with edge effects when using local kriging (#5)
 - [ ] Map units vs. km. How to handle this (#12)
 - [ ] Wrong projections of exported shape and raster files (#13)
 - [ ] Too many areas with a specific site density caused by chosen grid spacing (#14)
 - [ ] Calculation of bbox diagonal and Kriging grid relies on vertices of Voronoi diagram and not on bbox created by `deldir::deldir`
